import {useMemo,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {ArrowLeft,Plus,Trash2,Save,CheckCircle2,Printer} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {Button,Field,PageHeader} from '../components/UI';
import {calculateCosting,money,uid} from '../utils/calculations';

const fresh={reference:'',supplierId:'',date:new Date().toISOString().slice(0,10),currency:'LKR',exchangeRate:1,invoice:'',notes:'',status:'Draft',items:[],costs:[]};

export default function CostingBuilder(){
  const {id}=useParams(),{data,update,user}=useApp(),nav=useNavigate();
  const existing=data.costings.find(c=>c.id===id);
  const [form,setForm]=useState(existing||{...fresh,id:uid('CST')});
  const calc=useMemo(()=>calculateCosting(form),[form]);
  const locked=existing?.status==='Finalized';
  const supplier=data.suppliers.find(s=>s.id===form.supplierId);
  const change=(k,v)=>setForm(f=>({...f,[k]:v}));
  const addItem=()=>{const p=data.products[0];change('items',[...form.items,{productId:p?.id||'',quantity:1,unitPrice:0,weight:p?.weight||0,volume:p?.volume||0,retailPrice:0,wholesalePrice:0}])};
  const setItem=(i,k,v)=>change('items',form.items.map((x,j)=>j===i?{...x,[k]:v}:x));
  const addCost=()=>change('costs',[...form.costs,{type:data.costTypes[0],amount:0,method:'value'}]);
  const save=(status=form.status)=>{const record={...form,status,reference:form.reference||`IMP-${new Date().getFullYear()}-${String(data.costings.length+1).padStart(3,'0')}`};update('costings',cs=>existing?cs.map(c=>c.id===existing.id?record:c):[record,...cs]);update('audit',a=>[{id:uid('AUD'),user:user.name,action:`${existing?'Updated':'Created'} costing ${record.reference}`,date:new Date().toISOString(),oldValue:existing?.status||'—',newValue:status},...a]);nav('/costings')};
  const actions=<div className="action-row">{existing&&<Button variant="secondary" onClick={()=>window.print()}><Printer size={17}/>Print full report</Button>}{!locked&&<><Button variant="secondary" onClick={()=>save('Draft')}><Save size={17}/>Save draft</Button><Button onClick={()=>save('Finalized')}><CheckCircle2 size={17}/>Finalize</Button></>}</div>;
  return <><div className="print-heading"><h1>SUPUN GROUP OF COMPANIES</h1><h2>Complete Costing & Pricing Report</h2><p>{form.reference} · Printed {new Date().toLocaleDateString()}</p></div><button className="back" onClick={()=>nav('/costings')}><ArrowLeft/>Back to costings</button><PageHeader eyebrow={existing?'COSTING DETAILS':'NEW COSTING'} title={existing?form.reference:'Create a costing'} description={locked?'This financial record is finalized and read-only.':'Enter shipment details, products and shared costs.'} action={actions}/><fieldset disabled={locked} className="builder">
    <section className="card section"><div className="section-title"><span>1</span><div><h2>Shipment information</h2><p>General details and supplier invoice</p></div></div><div className="form-grid three"><Field label="Reference number"><input value={form.reference} placeholder="Auto-generated if blank" onChange={e=>change('reference',e.target.value)}/></Field><Field label="Supplier"><select required value={form.supplierId} onChange={e=>change('supplierId',e.target.value)}><option value="">Select supplier</option>{data.suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></Field><Field label="Costing date"><input type="date" value={form.date} onChange={e=>change('date',e.target.value)}/></Field><Field label="Currency"><select value={form.currency} onChange={e=>change('currency',e.target.value)}>{['LKR','USD','EUR','GBP','JPY','CNY'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Exchange rate to LKR"><input type="number" step="any" value={form.exchangeRate} onChange={e=>change('exchangeRate',e.target.value)}/></Field><Field label="Invoice reference"><input value={form.invoice} onChange={e=>change('invoice',e.target.value)}/></Field></div><div className="print-shipment"><div><span>Reference</span><b>{form.reference}</b></div><div><span>Supplier</span><b>{supplier?.name||'—'}</b></div><div><span>Date</span><b>{form.date}</b></div><div><span>Currency / Rate</span><b>{form.currency} / {form.exchangeRate}</b></div><div><span>Invoice</span><b>{form.invoice||'—'}</b></div><div><span>Status</span><b>{form.status}</b></div></div></section>
    <section className="card section"><div className="section-title"><span>2</span><div><h2>Products</h2><p>Supplier price, quantity and target selling prices</p></div><Button variant="secondary" onClick={addItem}><Plus size={17}/>Add product</Button></div>{form.items.length===0?<div className="empty">No products added yet.</div>:<div className="table-wrap editable input-products"><table><thead><tr><th>Product</th><th>Qty</th><th>Unit price</th><th>Weight</th><th>Volume</th><th>Retail price</th><th>Wholesale</th><th>Purchase cost</th><th></th></tr></thead><tbody>{calc.items.map((item,i)=><tr key={i}><td><select value={item.productId} onChange={e=>{const p=data.products.find(x=>x.id===e.target.value);setItem(i,'productId',e.target.value);setTimeout(()=>setForm(f=>({...f,items:f.items.map((x,j)=>j===i?{...x,weight:p.weight,volume:p.volume}:x)})),0)}}>{data.products.map(p=><option value={p.id} key={p.id}>{p.code} — {p.name}</option>)}</select></td>{['quantity','unitPrice','weight','volume','retailPrice','wholesalePrice'].map(k=><td key={k}><input type="number" min="0" step="any" value={item[k]} onChange={e=>setItem(i,k,e.target.value)}/></td>)}<td><b>{money(item.purchaseCost)}</b></td><td><button className="icon-btn danger" onClick={()=>change('items',form.items.filter((_,j)=>j!==i))}><Trash2 size={17}/></button></td></tr>)}</tbody></table></div>}</section>
    <section className="card section"><div className="section-title"><span>3</span><div><h2>Additional costs & allocation</h2><p>Shared expenses distributed across products</p></div><Button variant="secondary" onClick={addCost}><Plus size={17}/>Add cost</Button></div>{form.costs.length===0?<div className="empty">No additional costs.</div>:<><div className="cost-inputs">{form.costs.map((cost,i)=><div className="cost-row" key={i}><Field label="Cost type"><select value={cost.type} onChange={e=>change('costs',form.costs.map((x,j)=>j===i?{...x,type:e.target.value}:x))}>{data.costTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Amount"><input type="number" min="0" value={cost.amount} onChange={e=>change('costs',form.costs.map((x,j)=>j===i?{...x,amount:e.target.value}:x))}/></Field><Field label="Allocate by"><select value={cost.method} onChange={e=>change('costs',form.costs.map((x,j)=>j===i?{...x,method:e.target.value}:x))}><option value="value">Product value</option><option value="quantity">Quantity</option><option value="weight">Weight</option><option value="volume">Volume</option></select></Field><button className="icon-btn danger" onClick={()=>change('costs',form.costs.filter((_,j)=>j!==i))}><Trash2/></button></div>)}</div><div className="print-costs table-wrap"><table><thead><tr><th>Cost type</th><th>Amount</th><th>Allocation method</th></tr></thead><tbody>{form.costs.map((c,i)=><tr key={i}><td>{c.type}</td><td>{money(c.amount)}</td><td>{c.method==='value'?'Product value':c.method}</td></tr>)}</tbody></table></div></>}</section>
    <section className="card section results"><div className="section-title"><span>4</span><div><h2>Landed cost, selling prices & profitability</h2><p>Complete calculated result per product</p></div></div><div className="summary-strip"><div><span>Purchase total</span><b>{money(calc.purchaseTotal)}</b></div><div><span>Additional costs</span><b>{money(calc.additionalTotal)}</b></div><div className="grand"><span>Total landed cost</span><b>{money(calc.landedTotal)}</b></div></div><div className="table-wrap"><table className="profit-table"><thead><tr><th>Product</th><th>Qty</th><th>Purchase</th><th>Allocated</th><th>Total landed</th><th>Unit landed</th><th>Retail price</th><th>R profit</th><th>R markup</th><th>R margin</th><th>Wholesale</th><th>W profit</th><th>W markup</th><th>W margin</th></tr></thead><tbody>{calc.items.map((x,i)=><tr key={i}><td><b>{data.products.find(p=>p.id===x.productId)?.name}</b><small>{data.products.find(p=>p.id===x.productId)?.code}</small></td><td>{x.quantity}</td><td>{money(x.purchaseCost)}</td><td>{money(x.allocatedCost)}</td><td>{money(x.totalLandedCost)}</td><td><b>{money(x.unitLandedCost)}</b></td><td>{money(x.retailPrice)}</td><td className={x.pricing.retail.profit>=0?'positive':'negative'}>{money(x.pricing.retail.profit)}</td><td>{x.pricing.retail.markup.toFixed(1)}%</td><td>{x.pricing.retail.margin.toFixed(1)}%</td><td>{money(x.wholesalePrice)}</td><td className={x.pricing.wholesale.profit>=0?'positive':'negative'}>{money(x.pricing.wholesale.profit)}</td><td>{x.pricing.wholesale.markup.toFixed(1)}%</td><td>{x.pricing.wholesale.margin.toFixed(1)}%</td></tr>)}</tbody></table></div></section>
  </fieldset></>
}
