import {useState} from 'react';
import {Eye,MapPin,Pencil,Plus,Trash2,Truck} from 'lucide-react';
import {useApp} from '../context/AppContext';
import {Button,Field,Modal,PageHeader,SearchBox} from '../components/UI';
import {uid} from '../utils/calculations';

const blank={name:'',country:'',currency:'USD',contact:'',notes:''};

export default function Suppliers(){
  const {data,update,user}=useApp();
  const [q,setQ]=useState('');
  const [modal,setModal]=useState(false);
  const [editing,setEditing]=useState(null);
  const [viewing,setViewing]=useState(null);
  const [form,setForm]=useState(blank);
  const list=data.suppliers.filter(s=>(s.name+s.country+s.contact).toLowerCase().includes(q.toLowerCase()));
  const openAdd=()=>{setEditing(null);setForm(blank);setModal(true)};
  const openEdit=s=>{setEditing(s.id);setForm({...blank,...s});setModal(true)};
  const close=()=>{setModal(false);setEditing(null);setForm(blank)};
  const save=e=>{e.preventDefault();const record={...form,id:editing||uid('SUP')};update('suppliers',items=>editing?items.map(x=>x.id===editing?record:x):[...items,record]);update('audit',logs=>[{id:uid('AUD'),user:user.name,action:`${editing?'Updated':'Created'} supplier ${record.name||record.id}`,date:new Date().toISOString(),oldValue:editing?'Existing details':'—',newValue:record.name||'Unnamed supplier'},...logs]);close()};
  const remove=s=>{const linked=data.costings.filter(c=>c.supplierId===s.id).length;if(!window.confirm(`Delete ${s.name||'this supplier'}? ${linked?`${linked} shipment(s) will keep their financial data but the supplier link will be cleared.`:'This action cannot be undone.'}`))return;update('suppliers',items=>items.filter(x=>x.id!==s.id));update('costings',items=>items.map(c=>c.supplierId===s.id?{...c,supplierId:'',supplierNameSnapshot:s.name}:c));update('audit',logs=>[{id:uid('AUD'),user:user.name,action:`Deleted supplier ${s.name||s.id}`,date:new Date().toISOString(),oldValue:s.name||s.id,newValue:'Deleted'},...logs]);if(viewing?.id===s.id)setViewing(null)};
  return <><PageHeader eyebrow="MASTER DATA" title="Suppliers" description="Add, view, edit and manage supplier information." action={<Button onClick={openAdd}><Plus size={18}/>Add supplier</Button>}/><div className="toolbar standalone"><SearchBox value={q} onChange={setQ}/><span>{list.length} suppliers</span></div><div className="supplier-grid">{list.map(s=><div className="supplier-card" key={s.id}><div className="supplier-icon"><Truck/></div><div><h3>{s.name||'Unnamed supplier'}</h3><p><MapPin size={15}/>{s.country||'No country'}</p></div><span className="currency">{s.currency||'—'}</span><dl><div><dt>Contact</dt><dd>{s.contact||'—'}</dd></div><div><dt>Notes</dt><dd>{s.notes||'—'}</dd></div></dl><div className="supplier-actions"><Button variant="secondary" onClick={()=>setViewing(s)}><Eye size={15}/>View</Button><Button variant="secondary" onClick={()=>openEdit(s)}><Pencil size={15}/>Edit</Button><Button variant="danger" onClick={()=>remove(s)}><Trash2 size={15}/>Delete</Button></div></div>)}</div>{viewing&&<Modal title="Supplier details" onClose={()=>setViewing(null)}><div className="supplier-view"><div className="supplier-view-head"><div className="supplier-icon"><Truck/></div><div><h2>{viewing.name||'Unnamed supplier'}</h2><p>{viewing.country||'No country'} · {viewing.currency||'No currency'}</p></div></div><dl><div><dt>Contact details</dt><dd>{viewing.contact||'—'}</dd></div><div><dt>Notes</dt><dd>{viewing.notes||'—'}</dd></div><div><dt>Related shipments</dt><dd>{data.costings.filter(c=>c.supplierId===viewing.id).length}</dd></div></dl><div className="form-actions"><Button variant="secondary" onClick={()=>setViewing(null)}>Close</Button><Button onClick={()=>{setViewing(null);openEdit(viewing)}}><Pencil size={15}/>Edit supplier</Button></div></div></Modal>}{modal&&<Modal title={editing?'Edit supplier':'Add supplier'} onClose={close}><form onSubmit={save} className="form-grid"><Field label="Supplier name"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Country"><input value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></Field><Field label="Currency"><select value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{['LKR','USD','EUR','GBP','JPY','CNY'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Contact details"><input value={form.contact} onChange={e=>setForm({...form,contact:e.target.value})}/></Field><Field label="Notes"><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><div className="form-actions"><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button>{editing?'Update supplier':'Save supplier'}</Button></div></form></Modal>}</>
}
